#!/bin/bash

# install by: sudo -H pip3 install xacro4sdf
echo 'you might want to first modify: <xacro_define_property name="conveyor_name" value="conveyor_belt_a" /> (inside model.sdf.xacro)'

xacro4sdf model.sdf.xacro

echo 'model.sdf generated...'
